# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
cat /home/vagrant/.ssh/mgmt.pub >> /home/vagrant/.ssh/authorized_keys
rm -f /home/vagrant/.ssh/mgmt.pub

apt-get update
apt-get install -y python-minimal
SCRIPT

Vagrant.configure("2") do |config|

  # create mgmt nodeapt
  config.vm.define :mgmt do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/xenial64"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.22.4"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      mgmt_config.vm.provision "file", source: "~/jmkey.pub", destination: "~/.ssh/id_rsa.pub"
      mgmt_config.vm.provision "file", source: "~/jmkey.prv", destination: "~/.ssh/id_rsa"
      mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  # create load balancer
  config.vm.define :lb do |lb_config|
      lb_config.vm.box = "ubuntu/xenial64"
      lb_config.vm.hostname = "lb"
      lb_config.vm.network :private_network, ip: "10.0.22.5"
      lb_config.vm.network "forwarded_port", guest: 80, host: 8080
      lb_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      lb_config.vm.provision "file", source: "~/jmkey.pub", destination: "~/.ssh/mgmt.pub"
      lb_config.vm.provision "shell", inline: $script
  end

  # create some web servers
  # https://docs.vagrantup.com/v2/vagrantfile/tips.html
  (1..4).each do |i|
    config.vm.define "web#{i}" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "web#{i}"
        node.vm.network :private_network, ip: "10.0.15.2#{i}"
        node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
        end
        node.vm.provision "file", source: "~/jmkey.pub", destination: "~/.ssh/mgmt.pub"
        node.vm.provision "shell", inline: $script
    end
  end

end
